flowchart TD
    daimon["daimon<br/><span style='font-size:smaller'>Provides a command-line interface and web application for interacting with ph...</span>"]
    subgraph external [external]
        ext_Click[("Click<br/><span style='font-size:smaller'>Command-line interface framework</span>")]
        ext_FastAPI[("FastAPI<br/><span style='font-size:smaller'>Web application framework</span>")]
        ext_LangGraph[("LangGraph<br/><span style='font-size:smaller'>Language model framework</span>")]
        ext_Pydantic[("Pydantic<br/><span style='font-size:smaller'>Data validation library</span>")]
        ext_Uvicorn[("Uvicorn<br/><span style='font-size:smaller'>ASGI server</span>")]
        ext_scikit_learn[("scikit-learn<br/><span style='font-size:smaller'>Machine learning library</span>")]
    end
